CREATE TABLE `wp_yoast_seo_meta` (  `object_id` bigint(20) unsigned NOT NULL,  `internal_link_count` int(10) unsigned DEFAULT NULL,  `incoming_link_count` int(10) unsigned DEFAULT NULL,  UNIQUE KEY `object_id` (`object_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_yoast_seo_meta` DISABLE KEYS */;
INSERT INTO `wp_yoast_seo_meta` VALUES('4239', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4238', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4237', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4236', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4235', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4234', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4233', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4232', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4231', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4230', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4229', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4228', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4227', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4226', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4225', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4224', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4223', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4222', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4221', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4220', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4213', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4214', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4215', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4216', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4217', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4218', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4219', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4212', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4240', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4241', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4242', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('4243', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('5384', '0', '0');
/*!40000 ALTER TABLE `wp_yoast_seo_meta` ENABLE KEYS */;
