CREATE TABLE `wp_term_taxonomy` (  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `taxonomy` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',  `count` bigint(20) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_taxonomy_id`),  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),  KEY `taxonomy` (`taxonomy`)) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_term_taxonomy` DISABLE KEYS */;
INSERT INTO `wp_term_taxonomy` VALUES('1', '1', 'category', '', '0', '1');
INSERT INTO `wp_term_taxonomy` VALUES('2', '2', 'nav_menu', '', '0', '8');
INSERT INTO `wp_term_taxonomy` VALUES('3', '3', 'nav_menu', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('4', '4', 'layout_category', '', '0', '3');
INSERT INTO `wp_term_taxonomy` VALUES('5', '5', 'scope', '', '0', '11');
INSERT INTO `wp_term_taxonomy` VALUES('6', '6', 'layout_type', '', '0', '1');
INSERT INTO `wp_term_taxonomy` VALUES('7', '7', 'module_width', '', '0', '1');
INSERT INTO `wp_term_taxonomy` VALUES('8', '8', 'product_type', '', '0', '1');
INSERT INTO `wp_term_taxonomy` VALUES('9', '9', 'product_type', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('10', '10', 'product_type', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('11', '11', 'product_type', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('12', '12', 'layout_type', '', '0', '9');
INSERT INTO `wp_term_taxonomy` VALUES('13', '13', 'module_width', '', '0', '15');
INSERT INTO `wp_term_taxonomy` VALUES('14', '14', 'layout_type', '', '0', '3');
INSERT INTO `wp_term_taxonomy` VALUES('15', '15', 'scope', '', '0', '5');
INSERT INTO `wp_term_taxonomy` VALUES('16', '16', 'layout_category', '', '0', '5');
INSERT INTO `wp_term_taxonomy` VALUES('17', '17', 'layout_type', '', '0', '3');
INSERT INTO `wp_term_taxonomy` VALUES('18', '18', 'layout_category', '', '0', '1');
INSERT INTO `wp_term_taxonomy` VALUES('19', '19', 'layout_category', '', '0', '4');
INSERT INTO `wp_term_taxonomy` VALUES('20', '20', 'layout_category', '', '0', '1');
/*!40000 ALTER TABLE `wp_term_taxonomy` ENABLE KEYS */;
