CREATE TABLE `wp_terms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `slug` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_id`),  KEY `slug` (`slug`(191)),  KEY `name` (`name`(191))) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_terms` DISABLE KEYS */;
INSERT INTO `wp_terms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `wp_terms` VALUES('2', 'main', 'main', '0');
INSERT INTO `wp_terms` VALUES('3', 'Main Menu', 'main-menu', '0');
INSERT INTO `wp_terms` VALUES('4', 'FW-Slider', 'fw-slider', '0');
INSERT INTO `wp_terms` VALUES('5', 'global', 'global', '0');
INSERT INTO `wp_terms` VALUES('6', 'module', 'module', '0');
INSERT INTO `wp_terms` VALUES('7', 'fullwidth', 'fullwidth', '0');
INSERT INTO `wp_terms` VALUES('8', 'simple', 'simple', '0');
INSERT INTO `wp_terms` VALUES('9', 'grouped', 'grouped', '0');
INSERT INTO `wp_terms` VALUES('10', 'variable', 'variable', '0');
INSERT INTO `wp_terms` VALUES('11', 'external', 'external', '0');
INSERT INTO `wp_terms` VALUES('12', 'section', 'section', '0');
INSERT INTO `wp_terms` VALUES('13', 'regular', 'regular', '0');
INSERT INTO `wp_terms` VALUES('14', 'layout', 'layout', '0');
INSERT INTO `wp_terms` VALUES('15', 'not_global', 'not_global', '0');
INSERT INTO `wp_terms` VALUES('16', 'footer', 'footer', '0');
INSERT INTO `wp_terms` VALUES('17', 'row', 'row', '0');
INSERT INTO `wp_terms` VALUES('18', 'Logos', 'logos', '0');
INSERT INTO `wp_terms` VALUES('19', 'Services', 'services', '0');
INSERT INTO `wp_terms` VALUES('20', 'FAQ', 'faq', '0');
/*!40000 ALTER TABLE `wp_terms` ENABLE KEYS */;
